name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: [cron: 30 12 * * 3, cron: 0 22 * * 5]
    

jobs:
  build-17-11:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [17, 11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'

      - name: Add permition to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Tests
        run: ./gradlew test

  build-13:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'

      - name: Add permition to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Tests
        run: ./gradlew test
