name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 12 * * 3'
    - cron: '0 22 * * 5'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Ensure Gradlew is Executable (Linux/MacOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            .\gradlew.bat build --no-daemon
          else
            ./gradlew build --no-daemon
          fi

      - name: Run Tests
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            .\gradlew.bat test --no-daemon
          else
            ./gradlew test --no-daemon
          fi
